### ISSUE TITLE
Possible Performance Improvment in eval_utils.py

### ISSUE THREAD

**Issue by william-silversmith** [ezequieldlrosa/isles22#4]
Hi! I was just browsing recent usages of cc3d to see how people are using it and I noticed there might be a way to make a possibly slow part faster:

https://github.com/ezequieldlrosa/isles22/blob/557a7530bc9a16912ea9052717d6075df8496770/utils/eval_utils.py#L185-L195

Give this a try.

```python
    intersection = np.logical_and(ground_truth, prediction)
    labeled_ground_truth, N = cc3d.connected_components(ground_truth, connectivity=connectivity, return_N=True)

    # Iterate over ground_truth clusters to find tp and fn.
    # tp and fn are only computed if the ground-truth is not empty.
    if N > 0:
        for binary_cluster_label in cc3d.each(labeled_ground_truth, binary=True, in_place=True):
            if np.logical_and(binary_cluster_image, intersection).any():
                tp += 1
            else:
                fn += 1
```

Another approach which might be able to totally do away with the quadratic performance might be to use [`fastremap.inverse_component_map`](https://github.com/seung-lab/fastremap) to match the intersection and labeled_ground_truth in one pass and then just evaluate the much smaller output.

```python
mapping = fastremap.inverse_component_map([ 1, 2, 1, 3 ], [ 4, 4, 5, 6 ]) # { 1: [ 4, 5 ], 2: [ 4 ], 3: [ 6 ] }
```

If there isn't much benefit for your project, please feel free to ignore this. I don't want to waste your time. Good luck on ISLES22!

**Comment by ezequieldlrosa** [comment]
Hi @william-silversmith, thanks for the feedback on this.
I tried to modify the code with your first block of changes, though isn't working:

```
    intersection = np.logical_and(ground_truth, prediction)
    labeled_ground_truth, N = cc3d.connected_components(ground_truth, connectivity=connectivity, return_N=True)

    # Iterate over ground_truth clusters to find tp and fn.
    # tp and fn are only computed if the ground-truth is not empty.
    if N > 0:
        for binary_cluster_image in cc3d.each(labeled_ground_truth, binary=True, in_place=True):
            if np.logical_and(binary_cluster_image, intersection).any():
                tp += 1
            else:
                fn += 1
```

> UnboundLocalError: local variable 'binary_cluster_image' referenced before assignment

It looks like the cc3d.each isnt returning/assigning a binary mask. Any idea?
Thanks!

**Comment by william-silversmith** [comment]
Whoops, sorry. I forgot to add in the other loop variable:

```python
for segid, binary_cluster_label in cc3d.each(labeled_ground_truth, binary=True, in_place=True):
```

**Comment by ezequieldlrosa** [comment]
great, now works :). Thanks for the feedback!
