### ISSUE TITLE
Can the mask be overlaid on the FLAIR images?

### ISSUE THREAD

**Issue by mohanatcs23** [ezequieldlrosa/isles22#5]
Hi @ezequieldlrosa, I went through the preprint and I understand the masks are generated for the DWI samples, but is there a possibility of using them with the FLAIR images, and if so, what kind of slice correspondence should be employed considering the FLAIR and masks have different channel as well as spatial resolutions?

Thanks for your time!

**Comment by ezequieldlrosa** [comment]
Dear @mohanatcs23 , 

Lesion masks are released in DWI space, only. If you want to use them in FLAIR space, then you should register DWI and FLAIR modalities, and project the masks to FLAIR.
We have released images 'as raw as possible', as this is the way images come from the imaging centers. Therefore, we opened them without almost no pre-processing, such that users can handle them at their convenience.

Warm regards,
Ezequiel
